"""Add cascade delete to Book.borrowings

Revision ID: 2fee91e7c565
Revises: 0c2a10c10988
Create Date: 2026-02-02 13:46:15.502574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fee91e7c565'
down_revision: Union[str, Sequence[str], None] = '0c2a10c10988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
