"""add published_year and copies_available to books

Revision ID: 8550be6fa608
Revises: f55863fb10e9
Create Date: 2026-01-29 19:26:17.825508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8550be6fa608'
down_revision: Union[str, Sequence[str], None] = 'f55863fb10e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('copies_available', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'copies_available')
    op.drop_column('books', 'published_year')
    # ### end Alembic commands ###
