"""add due_date to borrowings

Revision ID: f31aed3b1de3
Revises: 8550be6fa608
Create Date: 2026-01-29 22:42:44.608332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31aed3b1de3'
down_revision: Union[str, Sequence[str], None] = '8550be6fa608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowings', sa.Column('due_date', sa.DateTime(), nullable=True))

    # Backfill existing rows
    op.execute(
        """
        UPDATE borrowings
        SET due_date = borrowed_at + INTERVAL '14 days'
        """
    )

    #  Make it NOT NULL
    op.alter_column(
        'borrowings',
        'due_date',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowings', 'due_date')
    # ### end Alembic commands ###
